### ISSUE TITLE
To-Do List (Deadline: 09/05)

### ISSUE THREAD

**Issue by gabriel-vieira06** [gabriel-vieira06/CalculoNumerico_ExercicioPrograma1#1]
# Lista de Afazeres

### Métodos:

- [x] Implementar método "conversaoNumerica" ('C' - Conversão);
- [x] Implementar método "recebeSistemaLinear" ('S' - Sistema Linear);
- [x] Implementar método "lerEquacaoAlgebrica" ('E' - Equação Algébrica);

[CALCULO NUMERICO EXERCICIO-PROGRAMA1.pdf](https://github.com/gabriel-vieira06/CalculoNumerico_ExercicioPrograma1/files/8564819/CALCULO.NUMERICO.EXERCICIO-PROGRAMA1.pdf)

**Comment by gabriel-vieira06** [comment]
Programa concluído, encerrando issue.
